# Generated by Django 2.2.4 on 2019-10-12 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100, unique=True)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('email_id', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField(max_length=100, unique=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_application.User')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='video_application.Video')),
            ],
        ),
    ]
